### ISSUE TITLE
[feat] meta태그 keywords추가

### ISSUE THREAD

**Issue by jihyun-Yun42** [EmoTrak/EmoTrak-FrontEnd#519]
meta태그 keywords에 검색엔진에 의해 검색되는 단어 지정 "EmoTrak"

**Comment by 1nxeo** [comment]
여러개 추가해도 상관없는거라면 emotrak 이외에도 감정일기 같은 키워드들 추가해보는건 어떨까요?

**Comment by jihyun-Yun42** [comment]
> 여러개 추가해도 상관없는거라면 emotrak 이외에도 감정일기 같은 키워드들 추가해보는건 어떨까요?

의견 반영해서 감정일기, 감정차트, 그림일기 키워드 추가했습니다!
`
<meta name="keywords" content="감정일기" />
<meta name="keywords" content="감정차트" />
<meta name="keywords" content="그림일기" />
`
